# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameNight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameNight
  pod "Parse"
  pod 'AlamofireImage'

  target 'GameNightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameNightUITests' do
    # Pods for testing
  end

end
